Update

diff --git a/bin/get-anime b/bin/get-anime
--- a/bin/get-anime
+++ b/bin/get-anime
@@ -1,10 +1,19 @@
 #!/bin/bash -e
 
 parent=/var/www/html
-log=/var/log/get-anime/$($HOME/dotfiles/bin/now)
+#log=/var/log/get-anime/$($HOME/dotfiles/bin/now)
+log=/var/log/get-anime.log
+
+trap catch ERR
+
+catch()
+{
+    echo "$($HOME/dotfiles/bin/now) error" >>$log
+}
+
 mkdir -p $(dirname $log)
-(
-set -x
+#(
+#set -x
 
 src='http://cal.syoboi.jp/rss2.php?usr=shiro51&filter=0&count=1000&days=14&titlefmt=%24(StTime)%01%24(Mark)%24(MarkW)%01%24(ShortTitle)%01%24(SubTitleB)%01%24(ChName)&alt=json'
 srcword='https://raw.githubusercontent.com/noyuno/dotfiles/master/list/anime-keyword'
@@ -14,5 +23,6 @@ destword=$parent/data/anime-keyword
 mkdir -p $(dirname $dest)
 curl -sL $src | jq . -M >$dest
 curl -sL $srcword >$destword
-) 1>$log 2>&1
+echo "$($HOME/dotfiles/bin/now) ok" >>$log
+#) 1>$log 2>&1
 
